version: '2.3'
services:
  redis:
    image: redis:5.0.3
    ports:
      - "6379:6379"
  jaeger:
    image: jaegertracing/all-in-one:1.24
    command: --log-level=debug
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411

  service:
    runtime: nvidia
    image: arruda/image-resizer-service:master
    command: python3 image_resizer_service/run.py
    build:
      context: '.'
      dockerfile: 'Dockerfile'

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=redis
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=jaeger
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${IMAGE_RESIZER_STREAM_KEY}
      - PUB_EVENT_TYPE_SERVICE_WORKER_ANNOUNCED=${EVENT_TYPE_SERVICE_WORKER_ANNOUNCED}
      - SERVICE_DETAILS_SERVICE_TYPE=ImageResizer
      - SERVICE_DETAILS_CONTENT_TYPES=none
      - SERVICE_DETAILS_STREAM_KEY=${IMAGE_RESIZER_STREAM_KEY}
      - SERVICE_DETAILS_QUEUE_LIMIT=100
      - SERVICE_DETAILS_THROUGHPUT=100
      - SERVICE_DETAILS_ACCURACY=1
      - SERVICE_DETAILS_ENERGY_CONSUMPTION=10
      - RESIZE_METHOD=${RESIZE_METHOD}